# ----
# Site

title: StrictLine.blog
url: "https://blog.strictline.biz"
baseurl: ""
google_analytics_key: G-43F1QE2103
show_full_navigation: true

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: My thoughts and discoveries to development of AuCRM (Aurea CRM / formerly update.CRM)
author: 
  name: Miklos Moricz, BSc.
  email: miklos.moricz@strictline.biz
social:
  name: GitHub
  links:
    - https://github.com/StrictLine

# -----
# Build 

timezone: Europe/Vienna

permalink: pretty

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

collections:
  docs:
    title: Documentation
    permalink: /:path/
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      path: ""
      type: "docs"
    values:
      seo:
        type: Article
      _comments:
        category: Group navigation links with this field
        order: Used to sort links in the navigation
      _options:
        content:
          width: 800
          height: 2000
  -
    scope:
      path: ""
      type: "posts"
    values:
      _comments:
        type: Marks the type of blog article

# -----------
# CloudCannon

types:
  - minor
  - major
